### PR TITLE
ci: fix broken CI pipeline

### PR DESCRIPTION
**Pull request by JaeAeich**
## Summary by Sourcery

Update Docker Compose command, pin pip version to <24.1, and add type hints.

Build:
- Pin pip version to <24.1 in the build process.

Pinning pip version because of dependency resolution issues in CI, since sooner or later this will be revisited and updated with pyproject, that will eventually update all the deps.

Chores:
- Update the Docker Compose command to use the new syntax.
- Add type hints to improve code maintainability.

### CODE REVIEW

**Comment by JaeAeich** [comment]
@sourcery-ai review

**Comment by uniqueg** [comment]
> Hey @JaeAeich - I've reviewed your changes - here's some feedback:
> 
> **Overall Comments**:
> - Consider splitting different types of changes (type hints, dependency updates, docker compose changes) into separate PRs for better review granularity
> - What's the rationale for strictly pinning foca to version 0.12.1? Using exact version pinning (==) instead of minimum version (>=) can make security updates more difficult
> 
> <details>
> <summary>Here's what I looked at during the review</summary>
> 
> - 🟢 **General issues**: all looks good
> - 🟢 **Security**: all looks good
> - 🟢 **Testing**: all looks good
> - 🟢 **Complexity**: all looks good
> - 🟢 **Documentation**: all looks good
> </details>
> 
> ***
> 
> <details>
> <summary>Sourcery is free for open source - if you like our reviews please consider sharing them ✨</summary>
> 
> - [X](https://twitter.com/intent/tweet?text=I%20just%20got%20an%20instant%20code%20review%20from%20%40SourceryAI%2C%20and%20it%20was%20brilliant%21%20It%27s%20free%20for%20open%20source%20and%20has%20a%20free%20trial%20for%20private%20code.%20Check%20it%20out%20https%3A//sourcery.ai)
> - [Mastodon](https://mastodon.social/share?text=I%20just%20got%20an%20instant%20code%20review%20from%20%40SourceryAI%2C%20and%20it%20was%20brilliant%21%20It%27s%20free%20for%20open%20source%20and%20has%20a%20free%20trial%20for%20private%20code.%20Check%20it%20out%20https%3A//sourcery.ai)
> - [LinkedIn](https://www.linkedin.com/sharing/share-offsite/?url=https://sourcery.ai)
> - [Facebook](https://www.facebook.com/sharer/sharer.php?u=https://sourcery.ai)
> 
> </details>
> 
> <sub>
> Help me be more useful! Please click 👍 or 👎 on each comment and I'll use the feedback to improve your reviews.
> </sub>

Generally a good comment, but in this case, we want to repair a broken CI because of outdated code. It makes sense to do so in one PR, especially since the changes are small.

**Comment by uniqueg** [comment]
> Hey @JaeAeich - I've reviewed your changes - here's some feedback:
> 
> **Overall Comments**:
> - Consider explaining the rationale for pinning pip to version <24.1 in the PR description. If this is addressing a specific issue, it might be better to fix the root cause rather than artificially constraining the pip version.
> 
> <details>
> <summary>Here's what I looked at during the review</summary>
> 
> - 🟢 **General issues**: all looks good
> - 🟢 **Security**: all looks good
> - 🟢 **Testing**: all looks good
> - 🟢 **Complexity**: all looks good
> - 🟢 **Documentation**: all looks good
> </details>
> 
> ***
> 
> <details>
> <summary>Sourcery is free for open source - if you like our reviews please consider sharing them ✨</summary>
> 
> - [X](https://twitter.com/intent/tweet?text=I%20just%20got%20an%20instant%20code%20review%20from%20%40SourceryAI%2C%20and%20it%20was%20brilliant%21%20It%27s%20free%20for%20open%20source%20and%20has%20a%20free%20trial%20for%20private%20code.%20Check%20it%20out%20https%3A//sourcery.ai)
> - [Mastodon](https://mastodon.social/share?text=I%20just%20got%20an%20instant%20code%20review%20from%20%40SourceryAI%2C%20and%20it%20was%20brilliant%21%20It%27s%20free%20for%20open%20source%20and%20has%20a%20free%20trial%20for%20private%20code.%20Check%20it%20out%20https%3A//sourcery.ai)
> - [LinkedIn](https://www.linkedin.com/sharing/share-offsite/?url=https://sourcery.ai)
> - [Facebook](https://www.facebook.com/sharer/sharer.php?u=https://sourcery.ai)
> 
> </details>
> 
> <sub>
> Help me be more useful! Please click 👍 or 👎 on each comment and I'll use the feedback to improve your reviews.
> </sub>

It may indeed be good to explain this. But no, we're gonna stick with the workaround for now.

**Review by uniqueg — APPROVED** [review]
Thanks for splitting up the PRs :+1: Please merge this first, then update the other PR.

And please address the one Sourcery comment by increasing your PR description (but that does not need re-review from my side).

**Comment by JaeAeich** [comment]
> Consider explaining the rationale for pinning pip to version <24.1 in the PR description. If this is addressing a specific issue, it might be better to fix the root cause rather than artificially constraining the pip version.

pining pip version because of dependency resolution issues in CI, since sooner or later this will be revisited and updated with pyproject, that will eventually update all the deps.

**Pull request merged**
