### PR TITLE
ENH: Allow uploading workflow attachments.

### PR DESCRIPTION
**Pull request by jvkersch**
**Details**

This is a small enhancement to allow for workflows to be submitted with workflow attachments. Workflow attachments are files that are uploaded with the POST request to run a workflow, and can contain the primary workflow, tools required to run the workflow, or input files needed to run the workflow.

The current implementation simply looks for attached files, and persists those to the `workflow_dir`. From there on, `cwl-tes` can be used to upload them to the remote storage when handling the TES request.

I did not add any tests but would be glad to do so, if necessary. The command that I use for smoke testing is
```
curl -X POST \
    --header 'Content-Type: multipart/form-data' \
    --header 'Accept: application/json' \
    -F workflow_params='{"input_file": {"class": "File", "location": "README.txt"}}' \
    -F workflow_type=CWL \
    -F workflow_type_version=v1.0 \
    -F workflow_url=cat-numbered.cwl \
    -F workflow_attachment="@cat-numbered.cwl" \
    -F workflow_attachment="@README.txt" \
    'http://localhost:8080/ga4gh/wes/v1/runs'
```
where `cat-numbered.cwl` simply runs an external tool on the input data, and `README.txt` is any random text file:
```
#!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: CommandLineTool
baseCommand: ["cat", "-n"]
inputs:
  input_file:
    type: File
    inputBinding:
      position: 1
outputs:
  result:
    type: stdout

stdout: output.txt
```

### CODE REVIEW

**Comment by uniqueg** [comment]
This is great - I've just wanted to do this! Thanks so much @jvkersch :)

Would you mind filing that same PR to [cwl-WES](https://github.com/elixir-cloud-aai/cwl-WES)? This repo (proWES), which is still under very early development and is eventually intended to be a Gateway API service for cwl-WES and other WES implementations (see schema here: https://github.com/elixir-cloud-aai/elixir-cloud-aai), is a fork of cwl-WES, so the PR will probably work 1:1. I would do it but don't want to rob your commit ;-)

Btw, in cwl-WES, there's actually an issue for this PR: elixir-cloud-aai/cwl-WES#6

**Comment by jvkersch** [comment]
Thanks @uniqueg! I've filed the PR to cwl-WES as https://github.com/elixir-cloud-aai/cwl-WES/pull/162.

Thanks also for your clarification regarding the role of proWES and cwl-WES. I had looked at the code before and was left wondering about the distinction, especially since I knew already about proTES and its interaction with TES services. Glad to see such a service for WES also taking shape.

I was also interested in the issue that you posted, and the underlying description of workflow attachments in the GA4GH standards. I use it (internally) as a way to write smoke tests, allowing a WES server to be tested in isolation (i.e. without DRS or TRS service).

**Comment by jvkersch** [comment]
@uniqueg Would you be OK with merging the PR here (in anticipation of elixir-cloud-aai/cwl-WES#162 going through review and getting merged)? Or would you prefer to wait for the cwl-WES PR to be merged first?

**Comment by uniqueg** [comment]
Sure @jvkersch, done!

**Pull request merged**
